# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Infineon Technologies AG
# SPDX-License-Identifier: MIT

name: REUSE
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v6
